apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  labels:
    app: node-app-1
spec:
  selector:
    app: node-app-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
